POST http://localhost:4000/patients
Content-Type: application/json

{
 "name":"Trisha Alu",
  "email":"alu@gmail.com",
  "address":"AUST 123 123 ",
  "dateOfBirth":"1950-09-09",
  "registeredDate":"1980-09-08"
}